-- MySQL Script generated by MySQL Workbench
-- Mon Nov 15 22:52:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sixtoArte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sixtoArte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sixtoArte` ;
-- -----------------------------------------------------
-- Schema sixtoArte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sixtoArte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sixtoArte` ;
USE `sixtoArte` ;

-- -----------------------------------------------------
-- Table `sixtoArte`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sixtoArte`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sixtoArte`.`colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sixtoArte`.`colors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sixtoArte`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sixtoArte`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `related` VARCHAR(400) NULL,
  `id_categoria` INT NULL,
  `id_colour` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_categoria_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `FK_id_color_idx` (`id_colour` ASC) VISIBLE,
  CONSTRAINT `FK_id_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `sixtoArte`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_id_color`
    FOREIGN KEY (`id_colour`)
    REFERENCES `sixtoArte`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sixtoArte`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sixtoArte`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `id_product` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_products_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `FK_id_products`
    FOREIGN KEY (`id_product`)
    REFERENCES `sixtoArte`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sixtoArte`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sixtoArte`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sixtoArte`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sixtoArte`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `birthday` DATE NULL,
  `email` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(200) NOT NULL,
  `avatar` VARCHAR(400) NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `FK_id_rol_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `FK_id_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `sixtoArte`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sixtoArte`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sixtoArte`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(200) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_usuario_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `FK_id_usershop`
    FOREIGN KEY (`id_user`)
    REFERENCES `sixtoArte`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sixtoArte`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sixtoArte`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_product` INT NOT NULL,
  `id_order` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_usuario_idx` (`id_user` ASC) VISIBLE,
  INDEX `FK_id_producto_idx` (`id_product` ASC) VISIBLE,
  INDEX `FK_id_order_idx` (`id_order` ASC) VISIBLE,
  CONSTRAINT `FK_id_usercart`
    FOREIGN KEY (`id_user`)
    REFERENCES `sixtoArte`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_id_productcart`
    FOREIGN KEY (`id_product`)
    REFERENCES `sixtoArte`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_id_order`
    FOREIGN KEY (`id_order`)
    REFERENCES `sixtoArte`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sixtoArte` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
